site_name: Schema Driven Configuration
nav:
  - Home: index.md
  - Getting Started:
    #- User guide: user_guide/introduction.md
    - Installation: getting-started/installation.md
    - Basic usage: basic_usage.md
    - User guide: getting-started/user-guide.md
  - Installation:
    - Overview: install/1_overview.md
    - Pre-Requisites: install/2_prereq.md
    - Kubernetes-collocated: install/3_k8s_collocated.md
    - Kubernetes-distributed: install/4_k8s_distributed.md
  - User guide:
    - Introduction: user_guide/introduction.md
    - Configuration:
      - Defining and loading Schema: crds/schema.md
      - Discovery: #crds/discovery_rule.md
        - Intro: crds/discovery_rule.md
        - Static: crds/discovery_rule.md
        - Dynamic: crds/discovery_rule.md
      - Target Profiles: # crds/discovery_rule.md
        - Target: crds/target.md
        - Connection Profile: crds/target_conn_profile.md
        - Sync Profile: crds/target_sync_profile.md
        - Credentials: crds/target_sync_profile.md
      - Config snippets: crds/config.md
  - System architecture:
      - Components:
        - Schema-server: concepts/schema_server.md
        - Data-server: concepts/data_server.md
        - Cache: concepts/cache.md
        - Config-server: concepts/config_server.md
  - Deployment Examples:
    - Intro: placeholder.md
    - Collocated deployment: placeholder.md
    - Distributed deployment: placeholder.md
    - K8s Collocated deployment: placeholder.md
    - K8s Distributed deployment: placeholder.md
  - Lab Examples:
    - About: examples/0_about.md
    - K8s with gNMI devices (SR Linux): examples/1_k8s_srl_collocated.md
    - K8s with NETCONF devices (SROS): examples/2_k8s_sros_collocated.md
  - Release Notes:
    - "0.0.1": rn/0.0.1.md
  - FAQ: faq/faq.md
  - Community: 
    - About: community/community.md
    - Contributing:
      - About: dev/about.md
      - Ways to contribute: dev/about.md

site_author: Wim Henderickx
site_description: >-
  Schema driven configuration is a system to configure devices through schema's (e.g. YANG) 
# repository
repo_name: sdcio/docs
repo_url: https://github.com/sdcio/docs
site_url: "https://docs.sdcio.dev"
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    #- header.autohide
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.integrate
    - toc.follow
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/flask
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/flask.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sdcio
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6P8mDvAh
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: sdcio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
      # dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
